version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: local_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: localdb
    ports:
      - '15432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dev -d localdb']
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: local_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev123
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: local_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev123
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  auction-service:
    image: robinhaider/auction-service:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=localdb;Username=dev;Password=dev123;
      IdentityServiceUrl: http://identity-service:5001
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: dev
      RabbitMQ__Password: dev123
    ports:
      - '7006:80'
    depends_on:
      - postgres
      - rabbitmq

  search-service:
    image: robinhaider/search-service:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__MongoDbConnection: mongodb://dev:dev123@mongodb:27017
      AuctionServiceUrl: http://auction-service
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: dev
      RabbitMQ__Password: dev123
    ports:
      - '7005:80'
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  postgres_data:
  mongodb_data:
  rabbitmq_data:
