version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: local_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: localdb
    ports:
      - '15432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dev -d localdb']
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: local_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev123
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          '--quiet',
          '127.0.0.1/test',
          '--eval',
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 40s

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: local_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev123
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 5

  auction-service:
    image: robinhaider/auction-service:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=localdb;Username=dev;Password=dev123;
      IdentityServiceUrl: http://identity-service:5001
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: dev
      RabbitMQ__Password: dev123
    ports:
      - '7006:80'
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  search-service:
    image: robinhaider/search-service:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__MongoDbConnection: mongodb://dev:dev123@mongodb:27017
      AuctionServiceUrl: http://auction-service
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: dev
      RabbitMQ__Password: dev123
    ports:
      - '7005:80'
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  gateway-service:
    image: robinhaider/gateway-service:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:80
    ports:
      - '6001:80'

  identity-service:
    image: robinhaider/identity-service:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=identity;Username=dev;Password=dev123;
    ports:
      - '5001:80'
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  mongodb_data:
  rabbitmq_data:
